version: '3.8'
services:
  eureka-service-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    volumes:
      - ./logs:/app/logs